import re

def mora2phoneme_text2phoneme(text):
    table2 = {"キャ": "k j a",
              "キュ": "k j ɯ",
              "キョ": "k j o",
              "ギャ": "g j a",
              "ギュ": "g j ɯ",
              "ギョ": "g j o",
              "シャ": "ɕ a",
              "シュ": "ɕ ɯ",
              "シェ": "ɕ e",
              "ショ": "ɕ o",
              "ジャ": "d ʑ a",
              "ジュ": "d ʑ ɯ",
              "ジェ": "d ʑ e",
              "ジョ": "d ʑ o",
              "チャ": "t ɕ a",
              "チュ": "t ɕ ɯ",
              "チェ": "t ɕ e",
              "チョ": "t ɕ o",
              "ニャ": "n j a",
              "ニュ": "n j ɯ",
              "ニョ": "n j o",
              "ヒャ": "ç j a",
              "ヒュ": "ç j ɯ",
              "ヒョ": "ç j o",
              "ピャ": "p j a",
              "ピュ": "p j ɯ",
              "ピョ": "p j o",
              "ビャ": "b j a",
              "ビュ": "b j ɯ",
              "ビョ": "b j o",
              "ミャ": "m j a",
              "ミュ": "m j ɯ",
              "ミョ": "m j o",
              "リャ": "ɾ j a",
              "リュ": "ɾ j ɯ",
              "リョ": "ɾ j o",
              "ティ": "t i",
              "ディ": "d i",
              "トゥ": "t ɯ",
              "ドゥ": "d ɯ",
              "デュ": "d j ɯ",
              "ツァ": "t s a",
              "ツェ": "t s e",
              "ツォ": "t s o",
              "スィ": "s i",
              "ズィ": "z i",
              "ファ": "ɸ a",
              "フィ": "ɸ i",
              "フェ": "ɸ e",
              "フォ": "ɸ o",
              "ウィ": "w i",
              "ウェ": "w e"}
    table = {"ア": "a",
             "イ": "i",
             "ウ": "ɯ",
             "エ": "e",
             "オ": "o",
             "カ": "k a",
             "キ": "k i",
             "ク": "k ɯ",
             "ケ": "k e",
             "コ": "k o",
             "ガ": "g a",
             "ギ": "g i",
             "グ": "g ɯ",
             "ゲ": "g e",
             "ゴ": "g o",
             "サ": "s a",
             "シ": "ɕ i",
             "ス": "s ɯ",
             "セ": "s e",
             "ソ": "s o",
             "ザ": "z a",
             "ジ": "d ʑ i",
             "ズ": "z ɯ",
             "ゼ": "z e",
             "ゾ": "z o",
             "タ": "t a",
             "チ": "t ɕ i",
             "ツ": "t s ɯ",
             "テ": "t e",
             "ト": "t o",
             "ダ": "d a",
             "デ": "d e",
             "ド": "d o",
             "ナ": "n a",
             "ニ": "n i",
             "ヌ": "n ɯ",
             "ネ": "n e",
             "ノ": "n o",
             "ハ": "h a",
             "ヒ": "ç i",
             "フ": "ɸ ɯ",
             "ヘ": "h e",
             "ホ": "h o",
             "パ": "p a",
             "ピ": "p i",
             "プ": "p ɯ",
             "ペ": "p e",
             "ポ": "p o",
             "バ": "b a",
             "ビ": "b i",
             "ブ": "b ɯ",
             "ベ": "b e",
             "ボ": "b o",
             "マ": "m a",
             "ミ": "m i",
             "ム": "m ɯ",
             "メ": "m e",
             "モ": "m o",
             "ヤ": "j a",
             "ユ": "j ɯ",
             "ヨ": "j o",
             "ラ": "ɾ a",
             "リ": "ɾ i",
             "ル": "ɾ ɯ",
             "レ": "ɾ e",
             "ロ": "ɾ o",
             "ワ": "ɰᵝ a",
             "ン": "ɴ",
             "＃": "#"}
    text = text.replace(" ", "▁ ")
    for m, p in table2.items():
        text = text.replace(m, p + " ")
    for m, p in table.items():
        text = text.replace(m, p + " ")
    text = text.rstrip()
    text = text.replace(" ー", ": ")
    text = re.sub("ッ([^aiɯeo]*) ([aiɯeo])", r"\1: \2", text)
    text = re.sub("ッ([aiɯeo])", r"ʔ \1", text)
    text = re.sub("ッ$", "ʔ", text)

    return text

def mora2phoneme_jpn(text):
    table2 = {"キャ": "ky a",
              "キュ": "ky u",
              "キョ": "ky o",
              "ギャ": "gy a",
              "ギュ": "gy u",
              "ギョ": "gy o",
              "シャ": "sy a",
              "シュ": "sy u",
              "シェ": "sy e",
              "ショ": "sy o",
              "ジャ": "zy a",
              "ジュ": "zy u",
              "ジェ": "zy e",
              "ジョ": "zy o",
              "チャ": "ch a",
              "チュ": "ch u",
              "チェ": "ch e",
              "チョ": "ch o",
              "ニャ": "ny a",
              "ニュ": "ny u",
              "ニョ": "ny o",
              "ヒャ": "hy a",
              "ヒュ": "hy u",
              "ヒョ": "hy o",
              "ピャ": "py a",
              "ピュ": "py u",
              "ピョ": "py o",
              "ビャ": "by a",
              "ビュ": "by u",
              "ビョ": "by o",
              "ミャ": "my a",
              "ミュ": "my u",
              "ミョ": "my o",
              "リャ": "ry a",
              "リュ": "ry u",
              "リョ": "ry o",
              "ティ": "t i", # チと同じ
              "ディ": "d i", # cf. /z i/
              "トゥ": "t u", # ツと同じ
              "ドゥ": "d u", # cf. /z u/
              # "デュ": "dy u", # UUDBには出現しない
              "ツァ": "ts a",
              "ツェ": "ts e",
              "ツォ": "ts o",
              "スィ": "s i", # シと同じ
              "ズィ": "z i", # ジと同じ
              "ファ": "f a",
              "フィ": "f i",
              "フェ": "f e",
              "フォ": "f o",
              "ウィ": "w i",
              "ウェ": "w e"}
    table = {"ア": "a",
             "イ": "i",
             "ウ": "u",
             "エ": "e",
             "オ": "o",
             "カ": "k a",
             "キ": "k i",
             "ク": "k u",
             "ケ": "k e",
             "コ": "k o",
             "ガ": "g a",
             "ギ": "g i",
             "グ": "g u",
             "ゲ": "g e",
             "ゴ": "g o",
             "サ": "s a",
             "シ": "s i",
             "ス": "s u",
             "セ": "s e",
             "ソ": "s o",
             "ザ": "z a",
             "ジ": "z i",
             "ズ": "z u",
             "ゼ": "z e",
             "ゾ": "z o",
             "タ": "t a",
             "チ": "t i",
             "ツ": "t u",
             "テ": "t e",
             "ト": "t o",
             "ダ": "d a",
             "ヂ": "z i", # ジと同じ
             "ヅ": "z u", # ズと同じ
             "デ": "d e",
             "ド": "d o",
             "ナ": "n a",
             "ニ": "n i",
             "ヌ": "n u",
             "ネ": "n e",
             "ノ": "n o",
             "ハ": "h a",
             "ヒ": "h i",
             "フ": "h u",
             "ヘ": "h e",
             "ホ": "h o",
             "パ": "p a",
             "ピ": "p i",
             "プ": "p u",
             "ペ": "p e",
             "ポ": "p o",
             "バ": "b a",
             "ビ": "b i",
             "ブ": "b u",
             "ベ": "b e",
             "ボ": "b o",
             "マ": "m a",
             "ミ": "m i",
             "ム": "m u",
             "メ": "m e",
             "モ": "m o",
             "ヤ": "y a",
             "ユ": "y u",
             "ヨ": "y o",
             "ラ": "r a",
             "リ": "r i",
             "ル": "r u",
             "レ": "r e",
             "ロ": "r o",
             "ワ": "w a",
             "ン": "N",
             "ッ": "Q",
             "＃": "#"}
    text = text.replace(" ", "sp")
    for m, p in table2.items():
        text = text.replace(m, p + " ")
    for m, p in table.items():
        text = text.replace(m, p + " ")
    text = text.rstrip()
    text = text.replace(" ー", ": ")

    return text

class Phonemizer:

    def __init__(self, mora2phoneme=mora2phoneme_jpn):
        self.mora2phoneme = mora2phoneme

    def __call__(self, text):
        return self.mora2phoneme(text)
